"""Add InspectionCriterion

Revision ID: 27803b17fb82
Revises: 36334ac2dc50
Create Date: 2025-11-27 16:10:03.924036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27803b17fb82'
down_revision = '36334ac2dc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgr_v_sp_ger_insp_krit',
    sa.Column('fid_spielgeraet', sa.BigInteger(), nullable=False),
    sa.Column('id_inspektionsart', sa.BigInteger(), nullable=False),
    sa.Column('fid_inspektionskriterium', sa.BigInteger(), nullable=False),
    sa.Column('inspektionsart', sa.String(length=255), nullable=True),
    sa.Column('bereich', sa.String(length=80), nullable=True),
    sa.Column('pruefung', sa.String(length=255), nullable=True),
    sa.Column('pruefung_kurztext', sa.String(length=255), nullable=True),
    sa.Column('wartung', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fid_spielgeraet', 'id_inspektionsart', 'fid_inspektionskriterium')
    )
    with op.batch_alter_table('gr_v_spielgeraete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_gr_v_spielgeraete_geom'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gr_v_spielgeraete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gr_v_spielgeraete_geom'), ['geom'], unique=False)

    op.drop_table('wgr_v_sp_ger_insp_krit')
    # ### end Alembic commands ###
