"""Initial migration

Revision ID: 36334ac2dc50
Revises: 
Create Date: 2025-11-27 14:40:27.331325

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '36334ac2dc50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wgr_sp_dringlichkeit_tbd',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_value', sa.String(length=30), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wgr_sp_inspektionsart_tbd',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_value', sa.String(length=30), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wgr_sp_kontrolleur',
    sa.Column('fid', sa.BigInteger(), nullable=False),
    sa.Column('nachname', sa.String(length=80), nullable=True),
    sa.Column('vorname', sa.String(length=80), nullable=True),
    sa.Column('e_mail', sa.String(length=80), nullable=True),
    sa.Column('pwd', sa.String(length=80), nullable=True),
    sa.Column('registrierung_uuid', sa.String(length=36), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('letzter_anmeldeversuch', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('wgr_sp_spielgeraeteart_tbd',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_value', sa.String(length=30), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('active', sa.SmallInteger(), nullable=True),
    sa.Column('fid_norm', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wgr_sp_spielplatz',
    sa.Column('fid', sa.BigInteger(), nullable=False),
    sa.Column('fid_anlage', sa.BigInteger(), nullable=True),
    sa.Column('nummer', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('beschrieb', sa.String(length=255), nullable=True),
    sa.Column('erstellungskosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('oeffentlich', sa.SmallInteger(), nullable=True),
    sa.Column('id_period_visu_insp', sa.BigInteger(), nullable=True),
    sa.Column('dat_letzt_visu_insp', sa.DateTime(), nullable=True),
    sa.Column('dat_naech_visu_insp', sa.DateTime(), nullable=True),
    sa.Column('id_period_oper_insp', sa.BigInteger(), nullable=True),
    sa.Column('dat_letzt_oper_insp', sa.DateTime(), nullable=True),
    sa.Column('dat_naech_oper_insp', sa.DateTime(), nullable=True),
    sa.Column('id_period_haupt_insp', sa.BigInteger(), nullable=True),
    sa.Column('dat_letzt_haupt_insp', sa.DateTime(), nullable=True),
    sa.Column('dat_naech_haupt_insp', sa.DateTime(), nullable=True),
    sa.Column('strassenname', sa.String(length=40), nullable=True),
    sa.Column('hausnummer', sa.String(length=10), nullable=True),
    sa.Column('uuid', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('gr_v_spielgeraete',
    sa.Column('fid', sa.BigInteger(), nullable=False),
    sa.Column('id_pflegestufe', sa.BigInteger(), nullable=True),
    sa.Column('fid_spielplatz', sa.BigInteger(), nullable=True),
    sa.Column('laufnummer', sa.BigInteger(), nullable=True),
    sa.Column('id_haupt_fallschutz', sa.BigInteger(), nullable=True),
    sa.Column('id_neben_fallschutz', sa.BigInteger(), nullable=True),
    sa.Column('lebensdauer', sa.SmallInteger(), nullable=True),
    sa.Column('sanierungsjahr', sa.SmallInteger(), nullable=True),
    sa.Column('abbruchjahr', sa.SmallInteger(), nullable=True),
    sa.Column('id_geraeteart', sa.BigInteger(), nullable=True),
    sa.Column('id_lieferant', sa.BigInteger(), nullable=True),
    sa.Column('bemerkungen', sa.String(length=100), nullable=True),
    sa.Column('norm', sa.String(length=255), nullable=True),
    sa.Column('verbindungen_s_n', sa.SmallInteger(), nullable=True),
    sa.Column('bew_teil_aufhaengung', sa.SmallInteger(), nullable=True),
    sa.Column('bew_teil_drehend', sa.SmallInteger(), nullable=True),
    sa.Column('bew_teil_federn', sa.SmallInteger(), nullable=True),
    sa.Column('bew_teil_ringe', sa.SmallInteger(), nullable=True),
    sa.Column('seile', sa.SmallInteger(), nullable=True),
    sa.Column('stahlseile', sa.SmallInteger(), nullable=True),
    sa.Column('ketten', sa.SmallInteger(), nullable=True),
    sa.Column('kustst_gummi', sa.SmallInteger(), nullable=True),
    sa.Column('holz', sa.SmallInteger(), nullable=True),
    sa.Column('allg_metallteile', sa.SmallInteger(), nullable=True),
    sa.Column('lackierter_stahl', sa.SmallInteger(), nullable=True),
    sa.Column('verzinkung', sa.SmallInteger(), nullable=True),
    sa.Column('aluminium', sa.SmallInteger(), nullable=True),
    sa.Column('fangstellen', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('kostenschaetzung', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('empfohlenes_sanierungsjahr', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('bemerkung_empf_sanierung', sa.String(length=255), nullable=True),
    sa.Column('geom', sa.String() if op.get_context().dialect.name == 'sqlite' else geoalchemy2.types.Geometry(geometry_type='POINT', srid=2056, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('picture_base64', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['fid_spielplatz'], ['wgr_sp_spielplatz.fid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    with op.batch_alter_table('gr_v_spielgeraete', schema=None) as batch_op:
        batch_op.create_index('idx_gr_v_spielgeraete_geom', ['geom'], unique=False, postgresql_using='gist')

    op.create_table('wgr_sp_inspektion',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('fid_spielplatz', sa.Integer(), nullable=True),
    sa.Column('id_inspektionsart', sa.Integer(), nullable=True),
    sa.Column('datum_inspektion', sa.Date(), nullable=True),
    sa.Column('fid_kontrolleur', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.String(length=255), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fid_kontrolleur'], ['wgr_sp_kontrolleur.fid'], ),
    sa.ForeignKeyConstraint(['fid_spielplatz'], ['wgr_sp_spielplatz.fid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('wgr_sp_insp_bericht',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('tid_inspektion', sa.Integer(), nullable=True),
    sa.Column('fid_spielgeraet', sa.Integer(), nullable=True),
    sa.Column('fid_geraet_detail', sa.Integer(), nullable=True),
    sa.Column('inspektionsart', sa.String(length=80), nullable=True),
    sa.Column('datum_inspektion', sa.Date(), nullable=True),
    sa.Column('kontrolleur', sa.String(length=80), nullable=True),
    sa.Column('pruefung_text', sa.String(length=255), nullable=True),
    sa.Column('pruefung_erledigt', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('pruefung_kommentar', sa.String(length=255), nullable=True),
    sa.Column('wartung_text', sa.String(length=255), nullable=True),
    sa.Column('wartung_erledigung', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('wartung_kommentar', sa.String(length=255), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('fallschutz', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['fid_spielgeraet'], ['gr_v_spielgeraete.fid'], ),
    sa.ForeignKeyConstraint(['tid_inspektion'], ['wgr_sp_inspektion.tid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('wgr_sp_insp_mangel',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('tid_insp_bericht', sa.Integer(), nullable=True),
    sa.Column('id_dringlichkeit', sa.Numeric(precision=1, scale=0), nullable=True),
    sa.Column('beschrieb', sa.String(length=255), nullable=True),
    sa.Column('datum_erledigung', sa.Date(), nullable=True),
    sa.Column('fid_erledigung', sa.String(length=80), nullable=True),
    sa.Column('bemerkunng', sa.String(length=255), nullable=True),
    sa.Column('picture1_base64', sa.String(), nullable=True),
    sa.Column('picture2_base64', sa.String(), nullable=True),
    sa.Column('picture3_base64', sa.String(), nullable=True),
    sa.Column('picture1_base64_thumb', sa.String(), nullable=True),
    sa.Column('picture2_base64_thumb', sa.String(), nullable=True),
    sa.Column('picture3_base64_thumb', sa.String(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tid_insp_bericht'], ['wgr_sp_insp_bericht.tid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wgr_sp_insp_mangel')
    op.drop_table('wgr_sp_insp_bericht')
    op.drop_table('wgr_sp_inspektion')
    with op.batch_alter_table('gr_v_spielgeraete', schema=None) as batch_op:
        batch_op.drop_index('idx_gr_v_spielgeraete_geom', postgresql_using='gist')

    op.drop_table('gr_v_spielgeraete')
    op.drop_table('wgr_sp_spielplatz')
    op.drop_table('wgr_sp_spielgeraeteart_tbd')
    op.drop_table('wgr_sp_kontrolleur')
    op.drop_table('wgr_sp_inspektionsart_tbd')
    op.drop_table('wgr_sp_dringlichkeit_tbd')
    # ### end Alembic commands ###
